version: '3.1'

services:
    web:
        build: ./nginx
        container_name: nginx
        restart: on-failure
        volumes:
            - ./nginx:/etc/nginx/conf.d
        command: [nginx-debug, '-g', 'daemon off;']
        ports:
            - 8080:80
        depends_on:
            - db
            - app
        networks:
            - app-networks
    app:
        build: ./app
        container_name: app
        restart: unless-stopped
        entrypoint: dockerize -wait tcp://db:3306 -timeout 80s
        command: 'npm start'
        ports:
            - 3333:3333
        depends_on:
            - db
        networks:
            - app-networks

    db:
        image: mysql:5.7
        restart: always
        command: --innodb-use-native-aio=0
        container_name: db
        environment:
            - MYSQL_DATABASE=peopledb
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 33061:3306
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
            - ./db:/var/lib/mysql
        networks:
            - app-networks

networks:
    app-networks:
        driver: bridge
